### ISSUE TITLE
Clean up random `init` functions.

### ISSUE THREAD

**Issue by MrAwesomeRocks** [AlemSnyder/Fun-Game#30]
I N I T I A L I Z E R  L I S T

**Comment by AlemSnyder** [comment]
This will probably not happen.
`init` functions exist in terrain_mesh, and terrain. TerrainMesh objects can't be copped because that leads to deleting the buffer on the gpu, so they are initialized "in place". Terrain has multiple inits because some grass data is calculated before the initialization.
